# Generated by Django 4.2.7 on 2024-11-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_type_alter_variantitem_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantitem',
            name='file',
        ),
        migrations.AddField(
            model_name='variantitem',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
